//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int ItemID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<double> itemPrice { get; set; }
        public Nullable<int> ItemQuantity { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<double> GrandTotal { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> isStatus { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public string createdUserBy { get; set; }
        public string updatedUserBy { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
